name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          mkdir out
          echo "CoreSys build" > out/CoreSys.txt

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            out/CoreSys.txt

      - name: Delete Out
        run: |
          rm -rf out/
          